services:
  backend:
    build:
      context: ../backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=https://ubiquitous-xylophone-jjrwwpp45x66cpw65-8000.app.github.dev

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: anime_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: